# Generated by Django 6.1.1 on 2026-09-14 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='title',
            field=models.CharField(blank=True, default='Membre', max_length=100),
        ),
        migrations.AddField(
            model_name='workspace',
            name='description',
            field=models.TextField(blank=True, default='Espace de travail pour gerer vos projets et equipes.'),
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_comments', models.BooleanField(default=True)),
                ('notify_task_assigned', models.BooleanField(default=True)),
                ('notify_project_updates', models.BooleanField(default=True)),
                ('notify_due_date', models.BooleanField(default=True)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
