# Generated by Django 6.0.8 on 2026-09-20 07:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_end_date_project_is_archived_project_lead_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprint',
            name='is_active',
        ),
        migrations.AddField(
            model_name='sprint',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sprint',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='sprints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sprint',
            name='objective',
            field=models.TextField(blank=True, verbose_name='Objectif'),
        ),
        migrations.AddField(
            model_name='sprint',
            name='status',
            field=models.CharField(choices=[('upcoming', 'À venir'), ('active', 'En cours'), ('done', 'Terminé'), ('cancelled', 'Annulé')], default='upcoming', max_length=12),
        ),
    ]
