# Generated by Django 6.0.8 on 2026-09-17 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_options_task_due_date_task_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'A faire'), ('in_progress', 'En cours'), ('in_review', 'En revue'), ('done', 'Termine'), ('cancelled', 'Annulee')], default='todo', max_length=15),
        ),
    ]
